set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p')

syntax on

set termguicolors
set number
set laststatus=1

set clipboard=unnamed

set smartcase
set hlsearch

set undofile
set noswapfile
set autoread
set viminfo=""

set autoindent
set expandtab
set tabstop=4
set shiftwidth=4

hi VertSplit cterm=NONE

let g:netrw_liststyle=3
let g:netrw_banner=0

let g:mapleader=" "

noremap <leader>s :w<CR>
noremap <leader>q :q<CR>
noremap <leader>e :E<CR>

noremap <Tab> :bnext<CR>
noremap <S-Tab> :bprev<CR>

noremap <leader>h :wincmd h<CR> 
noremap <leader>j :wincmd j<CR> 
noremap <leader>k :wincmd k<CR> 
noremap <leader>l :wincmd l<CR> 

