[[language]]
name = "c"
auto-format = true

[[language]]
name = "cpp"
file-types = ["cc", "cpp", "cxx", "c++", "cu", "h", "hh", "hpp", "hxx", "h++"]
auto-format = true

[[language]]
name = "latex"
formatter = { command = "latexindent", args = ["-g", "/dev/null"] }
auto-format = true

[[language]]
name = "nix"
formatter = { command = "alejandra" }
auto-format = true

[[language]]
name = "python"
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {}
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "javascript"
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "tsconfig.json"]
language-server = { command = "deno", args = ["lsp"], language-id = "javascript" }
config = { enable = true, lint = true, unstable = true }
auto-format = true

[[language]]
name = "typescript"
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "tsconfig.json"]
language-server = { command = "deno", args = ["lsp"], language-id = "typescript" }
config = { enable = true, lint = true, unstable = true }
auto-format = true

[[language]]
name = "jsx"
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "tsconfig.json"]
language-server = { command = "deno", args = ["lsp"], language-id = "javascriptreact" }
config = { enable = true, lint = true, unstable = true }
auto-format = true

[[language]]
name = "tsx"
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "tsconfig.json"]
language-server = { command = "deno", args = ["lsp"], language-id = "typescriptreact" }
config = { enable = true, lint = true, unstable = true }
auto-format = true

